version: '3'
services:
  db:
    image: postgis/postgis:12-3.0
    container_name: postgis
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
    volumes:
      - postgis:/var/lib/postgresql/data
volumes:
  postgis:
