version: '3'
services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: mysql
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    ports:
      - "33060:3306"
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: